name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [node, ruby]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      if: matrix.language == 'node'
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Node.js dependencies
      if: matrix.language == 'node'
      run: npm install

    - name: Run Node.js tests
      if: matrix.language == 'node'
      run: npm test

    - name: Setup Ruby
      if: matrix.language == 'ruby'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Ruby dependencies
      if: matrix.language == 'ruby'
      run: bundle install

    - name: Run Ruby tests
      if: matrix.language == 'ruby'
      run: bundle exec rspec
