name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Build
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/**/*.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: app-bundle
        path: app/build/outputs/bundle/**/*.aab
